=== R3TR0R0C4/ASIX1/Examen XML/eleccions.dtd
<!ELEMENT eleccions (partit+)>
<!ATTLIST eleccions any CDATA  #REQUIRED >
<!ELEMENT partit (nom_partit, electors, congrés, senadors, candidat+)>
<!ELEMENT nom_partit (#PCDATA)>
<!ELEMENT estats (estat+)>
<!ELEMENT estat (#PCDATA)>
<!ELEMENT electors (#PCDATA)>
<!ELEMENT congrés (#PCDATA)>
<!ELEMENT senadors (#PCDATA)>
<!ELEMENT candidat (nom, edat, (primaries|president))>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT edat (#PCDATA)>
<!ELEMENT primaries EMPTY>
<!ELEMENT president EMPTY>

=== R3TR0R0C4/ASIX1/Examen XML/eleccions.xml
<!-- <!DOCTYPE eleccions SYSTEM "eleccions.dtd">-->
<!DOCTYPE eleccions SYSTEM "eleccions.dtd">
<eleccions any="2024">
	<partit>
		<nom_partit>Republicà</nom_partit>
		<electors>0</electors>
		<congrés>0</congrés>
		<senadors>0</senadors>
		<candidat>
			<nom>Donald Trump</nom>
			<edat>78</edat>
			<primaries/>
		</candidat>
	</partit>
	<partit>
		<nom_partit>Republicà</nom_partit>
		<estats>
		  <estat>New_Hampshire</estat>
		  <estat>Vermont</estat>
		</estats>
		<electors>7</electors>
		<congrés>0</congrés>
		<senat>0</senat>
		<candidat>
			<edat>82</edat>
			<nom>Joe Biden</nom>
			<president/>
		</candidat>
	</partit>
</eleccions>
